[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
    /(
        \.eggs/|
        \.git/|
        \.hg/|
        \.mypy_cache/|
        \.tox/|
        \.venv/|
        venv/|
        build/|
        buck-out/|
        build/|
        dist/
    ) 
'''

[tool.isort]
profile = "black"
skip = [".venv", "venv"]